/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Graphics;
import java.awt.Point;
import java.awt.image.BufferedImage;
import satimage.Tools;

/**
 *
 * @author Red
 */
public class ImagePanel extends javax.swing.JPanel {

    private Point offSet;
    private BufferedImage img;
    private Tools tools;
    
    public ImagePanel(BufferedImage bimg) {
        initComponents();
        tools = Tools.get();
        img = bimg;
        offSet = new Point(0,0);
    }
    
    public ImagePanel(BufferedImage bimg, int x, int y) {
        initComponents();
        tools = Tools.get();
        img = bimg;
        offSet = new Point(x,y);
    }
    /**
     * Surcharge du parent pour afficher une image
     * @param g les paramètres graphiques
     */
    @Override
    public void paint(Graphics g)
    {
        super.paint(g);
        g.drawImage(img, offSet.x, offSet.y, null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
